---
keycloak:
  ingress:
    enabled: true
    hosts:
      - keycloak.171.18.93.119.nip.io
    annotations:
      kubernetes.io/ingress.class: nginx
    tls:
      - secretName: keycloak-tls
        hosts:
          - keycloak.171.18.93.119.nip.io

  persistence:
    deployPostgres: true
    dbVendor: postgres
    dbPassword: changeme

postgresql:
  persistence:
    enabled: false
  postgresPassword: changeme