apiVersion: rbac.authorization.k8s.io/v1
# This cluster role allows default service account to read secrets in all namespaces
kind: ClusterRoleBinding
metadata:
  name: read-secrets-global
roleRef:
  kind: ClusterRole
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: default
    namespace: kube-system;p.